# ===============================
# PROJECT NAME : KATANA ML PROD
# ===============================


# Development Configurations
# ---------------------------
DEBUG : False


# Serving Configurations
# -----------------------
HOST : 0.0.0.0
PORT : 9000