# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=0_gnu
aniso8601=8.0.0=py_0
attrs=19.3.0=py_0
ca-certificates=2019.11.28=hecc5488_0
certifi=2019.11.28=py38_0
click=7.0=py_0
flask=1.1.1=py_1
flask-restplus=0.13.0=py38_0
importlib_metadata=1.5.0=py38_0
itsdangerous=1.1.0=py_0
jinja2=2.11.1=py_0
jsonschema=3.2.0=py38_0
ld_impl_linux-64=2.33.1=h53a641e_8
libffi=3.2.1=he1b5a44_1006
libgcc-ng=9.2.0=h24d8f2e_2
libgomp=9.2.0=h24d8f2e_2
libstdcxx-ng=9.2.0=hdf63c60_2
markupsafe=1.1.1=py38h516909a_0
ncurses=6.1=hf484d3e_1002
openssl=1.1.1d=h516909a_0
pip=20.0.2=py_2
pyrsistent=0.15.7=py38h516909a_0
python=3.8.2=h9d8adfe_4_cpython
python-dateutil=2.8.1=py_0
python_abi=3.8=1_cp38
pytz=2019.3=py_0
readline=8.0=hf8c457e_0
setuptools=46.0.0=py38_0
six=1.14.0=py38_0
sqlite=3.30.1=hcee41ef_0
tk=8.6.10=hed695b0_0
werkzeug=1.0.0=py_0
wheel=0.34.2=py_1
xz=5.2.4=h14c3975_1001
zipp=3.1.0=py_0
zlib=1.2.11=h516909a_1006
